#!/bin/sh /etc/rc.common
START=99

start(){
    kill -9 $(pgrep -f subconverter/subconverter)
    cd /etc/subconverter
    /etc/subconverter/subconverter > /dev/null 2>&1 &
}

stop(){
    kill -9 $(pgrep -f subconverter/subconverter)
}

restart(){
    kill -9 $(pgrep -f subconverter/subconverter)
    cd /etc/subconverter
    /etc/subconverter/subconverter > /dev/null 2>&1 &
}
