[Application]
FileLogger\Enabled=false

[BitTorrent]
Session\BTProtocol=Both
Session\CreateTorrentSubfolder=true
Session\DisableAutoTMMByDefault=true
Session\DisableAutoTMMTriggers\CategoryChanged=false
Session\DisableAutoTMMTriggers\CategorySavePathChanged=true
Session\DisableAutoTMMTriggers\DefaultSavePathChanged=true
Session\SeedChokingAlgorithm=FastestUpload
Session\TorrentContentLayout=Original

[Core]
AutoDeleteAddedTorrentFile=Never

[LegalNotice]
Accepted=true

[Network]
Cookies=@Invalid()

[Preferences]
Advanced\AnonymousMode=true
Advanced\IgnoreLimitsLAN=true
Advanced\IncludeOverhead=false
Advanced\SuperSeeding=false
Bittorrent\DHT=true
Bittorrent\Encryption=0
Bittorrent\LSD=true
Bittorrent\MaxRatioAction=0
Bittorrent\PeX=true
Bittorrent\uTP_rate_limited=true
Connection\PortRangeMin=55555
Connection\UPnP=true
Downloads\PreAllocation=false
Downloads\SavePath=/tmp/download
Downloads\StartInPause=false
Downloads\TempPath=temp/
Downloads\TempPathEnabled=true
Downloads\UseIncompleteExtension=false
General\Locale=zh
General\UseRandomPort=false
Queueing\QueueingEnabled=true
WebUI\AuthSubnetWhitelistEnabled=false
WebUI\CSRFProtection=false
WebUI\ClickjackingProtection=true
WebUI\HostHeaderValidation=true
WebUI\LocalHostAuth=true
WebUI\Port=8080
WebUI\UseUPnP=false
